name: Check Files
on: push
jobs:
  File_Checks:
    name: Run check files bash scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check images location
        run: |
         chmod +x ./.github/scripts/checkImagesLocation.sh
         ./.github/scripts/checkImagesLocation.sh
        shell: bash

      - name: Check sounds location
        run: |
         chmod +x ./.github/scripts/checkSoundsLocation.sh
         ./.github/scripts/checkSoundsLocation.sh
        shell: bash

      - name: Check repeated file names
        run: |
         chmod +x ./.github/scripts/checkFilenameDuplicated.sh
         ./.github/scripts/checkFilenameDuplicated.sh
        shell: bash

      - name: Check data files location
        run: |
         chmod +x ./.github/scripts/checkDataLocation.sh
         ./.github/scripts/checkDataLocation.sh
        shell: bash

