name: Check Files
on: push
jobs:
  File Checks:
    name: Run check files bash scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check images location
      run: |
        chmod +x ./.github/scripts/checkImgInImages.sh
        ./.github/scripts/checkImgInImages.sh
      shell: bash
