name: Check Files
on: push
jobs:
  Check_image_files:
    name: Run check images location bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check images files location
        run: |
         chmod +x ./.github/scripts/chImageLocation.sh
         ./.github/scripts/chImageLocation.sh
        shell: bash

  Check_sound_files:
    name: Run check sounds location bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check sounds files location
        run: |
         chmod +x ./.github/scripts/chSoundLocation.sh
         ./.github/scripts/chSoundLocation.sh
        shell: bash

  Check_data_files:
    name: Run check data files location bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check data files location
        run: |
         chmod +x ./.github/scripts/chDataLocation.sh
         ./.github/scripts/chDataLocation.sh
        shell: bash

  Check_repeated_filenames:
    name: Run check filenames duplicated bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check repeated file names
        run: |
         chmod +x ./.github/scripts/checkFilenameDuplicated.sh
         ./.github/scripts/checkFilenameDuplicated.sh
        shell: bash

  Check_source_files:
    name: Run check source files location bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check source files location
        run:
         chmod +x ./.github/scripts/chSourceLocation.sh
         ./.github/scripts/chSourceLocation.sh
        shell: bash

  Check_image_size:
    name: Run check image size files bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check image files size
        run:
         chmod +x ./.github/scripts/chImageSize.sh
         ./.github/scripts/chImageSize.sh
        shell: bash

  Check_filenames_length:
    name: Run check filenames length bash script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check filenames length
        run:
         chmod +x ./.github/scripts/chFilenameLength.sh
         ./.github/scripts/chFilenameLength.sh
        shell: bash

      

      

