name: Bash Scripts
on: push
jobs:
  activation:
    name: Run test bash scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Simple echo
        run: |
         chmod +x ./.github/scripts/testbash.sh
         ./.github/scripts/testbash.sh
        shell: bash
